import { Seat } from "@/types/seat.types";

export const cinemaSeats: Seat[] = [
  {
    id: 30239,
    x: 0.0,
    y: 0.0,
    row: "1",
    seat: 1,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30240,
    x: 24.0,
    y: 0.0,
    row: "1",
    seat: 2,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30241,
    x: 48.0,
    y: 0.0,
    row: "1",
    seat: 3,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30242,
    x: 72.0,
    y: 0.0,
    row: "1",
    seat: 4,
    isSold: false,
    isReserved: true,
    isSelectable: false,
  },
  {
    id: 30243,
    x: 96.0,
    y: 0.0,
    row: "1",
    seat: 5,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30244,
    x: 120.0,
    y: 0.0,
    row: "1",
    seat: 6,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30245,
    x: 144.0,
    y: 0.0,
    row: "1",
    seat: 7,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30246,
    x: 168.0,
    y: 0.0,
    row: "1",
    seat: 8,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30247,
    x: 192.0,
    y: 0.0,
    row: "1",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30248,
    x: 216.0,
    y: 0.0,
    row: "1",
    seat: 10,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30249,
    x: 240.0,
    y: 0.0,
    row: "1",
    seat: 11,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30253,
    x: 0.0,
    y: 24.0,
    row: "2",
    seat: 1,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30254,
    x: 24.0,
    y: 24.0,
    row: "2",
    seat: 2,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30255,
    x: 48.0,
    y: 24.0,
    row: "2",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30256,
    x: 72.0,
    y: 24.0,
    row: "2",
    seat: 4,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30257,
    x: 96.0,
    y: 24.0,
    row: "2",
    seat: 5,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30258,
    x: 120.0,
    y: 24.0,
    row: "2",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30259,
    x: 144.0,
    y: 24.0,
    row: "2",
    seat: 7,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30260,
    x: 168.0,
    y: 24.0,
    row: "2",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30261,
    x: 192.0,
    y: 24.0,
    row: "2",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30262,
    x: 216.0,
    y: 24.0,
    row: "2",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30263,
    x: 240.0,
    y: 24.0,
    row: "2",
    seat: 11,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30264,
    x: 264.0,
    y: 24.0,
    row: "2",
    seat: 12,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30267,
    x: 0.0,
    y: 48.0,
    row: "3",
    seat: 1,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30268,
    x: 24.0,
    y: 48.0,
    row: "3",
    seat: 2,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30269,
    x: 48.0,
    y: 48.0,
    row: "3",
    seat: 3,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30270,
    x: 72.0,
    y: 48.0,
    row: "3",
    seat: 4,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30271,
    x: 96.0,
    y: 48.0,
    row: "3",
    seat: 5,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30272,
    x: 120.0,
    y: 48.0,
    row: "3",
    seat: 6,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30273,
    x: 144.0,
    y: 48.0,
    row: "3",
    seat: 7,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30274,
    x: 168.0,
    y: 48.0,
    row: "3",
    seat: 8,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30275,
    x: 192.0,
    y: 48.0,
    row: "3",
    seat: 9,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30276,
    x: 216.0,
    y: 48.0,
    row: "3",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30277,
    x: 240.0,
    y: 48.0,
    row: "3",
    seat: 11,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30278,
    x: 264.0,
    y: 48.0,
    row: "3",
    seat: 12,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30279,
    x: 288.0,
    y: 48.0,
    row: "3",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30281,
    x: 0.0,
    y: 72.0,
    row: "4",
    seat: 1,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30282,
    x: 24.0,
    y: 72.0,
    row: "4",
    seat: 2,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30283,
    x: 48.0,
    y: 72.0,
    row: "4",
    seat: 3,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30284,
    x: 72.0,
    y: 72.0,
    row: "4",
    seat: 4,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30285,
    x: 96.0,
    y: 72.0,
    row: "4",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30286,
    x: 120.0,
    y: 72.0,
    row: "4",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30287,
    x: 144.0,
    y: 72.0,
    row: "4",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30288,
    x: 168.0,
    y: 72.0,
    row: "4",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30289,
    x: 192.0,
    y: 72.0,
    row: "4",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30290,
    x: 216.0,
    y: 72.0,
    row: "4",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30291,
    x: 240.0,
    y: 72.0,
    row: "4",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 30292,
    x: 264.0,
    y: 72.0,
    row: "4",
    seat: 12,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30293,
    x: 288.0,
    y: 72.0,
    row: "4",
    seat: 13,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30295,
    x: 0.0,
    y: 96.0,
    row: "5",
    seat: 1,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30296,
    x: 24.0,
    y: 96.0,
    row: "5",
    seat: 2,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30297,
    x: 48.0,
    y: 96.0,
    row: "5",
    seat: 3,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30298,
    x: 72.0,
    y: 96.0,
    row: "5",
    seat: 4,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30299,
    x: 96.0,
    y: 96.0,
    row: "5",
    seat: 5,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30300,
    x: 120.0,
    y: 96.0,
    row: "5",
    seat: 6,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30301,
    x: 144.0,
    y: 96.0,
    row: "5",
    seat: 7,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30302,
    x: 168.0,
    y: 96.0,
    row: "5",
    seat: 8,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30303,
    x: 192.0,
    y: 96.0,
    row: "5",
    seat: 9,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30304,
    x: 216.0,
    y: 96.0,
    row: "5",
    seat: 10,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30305,
    x: 240.0,
    y: 96.0,
    row: "5",
    seat: 11,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30306,
    x: 264.0,
    y: 96.0,
    row: "5",
    seat: 12,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30307,
    x: 288.0,
    y: 96.0,
    row: "5",
    seat: 13,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 30308,
    x: 312.0,
    y: 96.0,
    row: "5",
    seat: 14,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
];
