import { Seat } from "@/types/seat.types";

export const concertSeats: Seat[] = [
  {
    id: 32549,
    x: 0,
    y: 0,
    row: "1",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32550,
    x: 24,
    y: 0,
    row: "1",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32551,
    x: 48,
    y: 0,
    row: "1",
    seat: 3,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32552,
    x: 72,
    y: 0,
    row: "1",
    seat: 4,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32553,
    x: 96,
    y: 0,
    row: "1",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32554,
    x: 120,
    y: 0,
    row: "1",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32555,
    x: 144,
    y: 0,
    row: "1",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32556,
    x: 168,
    y: 0,
    row: "1",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32557,
    x: 192,
    y: 0,
    row: "1",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32558,
    x: 216,
    y: 0,
    row: "1",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32559,
    x: 240,
    y: 0,
    row: "1",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32560,
    x: 264,
    y: 0,
    row: "1",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32561,
    x: 288,
    y: 0,
    row: "1",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32562,
    x: 312,
    y: 0,
    row: "1",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32563,
    x: 336,
    y: 0,
    row: "1",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32564,
    x: 360,
    y: 0,
    row: "1",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32565,
    x: 384,
    y: 0,
    row: "1",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32566,
    x: 408,
    y: 0,
    row: "1",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32567,
    x: 432,
    y: 0,
    row: "1",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32568,
    x: 456,
    y: 0,
    row: "1",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32574,
    x: 0,
    y: 24,
    row: "2",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32575,
    x: 24,
    y: 24,
    row: "2",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32576,
    x: 48,
    y: 24,
    row: "2",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32577,
    x: 72,
    y: 24,
    row: "2",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32578,
    x: 96,
    y: 24,
    row: "2",
    seat: 5,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32579,
    x: 120,
    y: 24,
    row: "2",
    seat: 6,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32580,
    x: 144,
    y: 24,
    row: "2",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32581,
    x: 168,
    y: 24,
    row: "2",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32582,
    x: 192,
    y: 24,
    row: "2",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32583,
    x: 216,
    y: 24,
    row: "2",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32584,
    x: 240,
    y: 24,
    row: "2",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32585,
    x: 264,
    y: 24,
    row: "2",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32586,
    x: 288,
    y: 24,
    row: "2",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32587,
    x: 312,
    y: 24,
    row: "2",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32588,
    x: 336,
    y: 24,
    row: "2",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32589,
    x: 360,
    y: 24,
    row: "2",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32590,
    x: 384,
    y: 24,
    row: "2",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32591,
    x: 408,
    y: 24,
    row: "2",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32592,
    x: 432,
    y: 24,
    row: "2",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32593,
    x: 456,
    y: 24,
    row: "2",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32594,
    x: 480,
    y: 24,
    row: "2",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32599,
    x: 0,
    y: 48,
    row: "3",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32600,
    x: 24,
    y: 48,
    row: "3",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32601,
    x: 48,
    y: 48,
    row: "3",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32602,
    x: 72,
    y: 48,
    row: "3",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32603,
    x: 96,
    y: 48,
    row: "3",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32604,
    x: 120,
    y: 48,
    row: "3",
    seat: 6,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32605,
    x: 144,
    y: 48,
    row: "3",
    seat: 7,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32606,
    x: 168,
    y: 48,
    row: "3",
    seat: 8,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32607,
    x: 192,
    y: 48,
    row: "3",
    seat: 9,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32608,
    x: 216,
    y: 48,
    row: "3",
    seat: 10,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32609,
    x: 240,
    y: 48,
    row: "3",
    seat: 11,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32610,
    x: 264,
    y: 48,
    row: "3",
    seat: 12,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32611,
    x: 288,
    y: 48,
    row: "3",
    seat: 13,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32612,
    x: 312,
    y: 48,
    row: "3",
    seat: 14,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32613,
    x: 336,
    y: 48,
    row: "3",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32614,
    x: 360,
    y: 48,
    row: "3",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32615,
    x: 384,
    y: 48,
    row: "3",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32616,
    x: 408,
    y: 48,
    row: "3",
    seat: 18,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32617,
    x: 432,
    y: 48,
    row: "3",
    seat: 19,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32618,
    x: 456,
    y: 48,
    row: "3",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32619,
    x: 480,
    y: 48,
    row: "3",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32624,
    x: 0,
    y: 72,
    row: "4",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32625,
    x: 24,
    y: 72,
    row: "4",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32626,
    x: 48,
    y: 72,
    row: "4",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32627,
    x: 72,
    y: 72,
    row: "4",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32628,
    x: 96,
    y: 72,
    row: "4",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32629,
    x: 120,
    y: 72,
    row: "4",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32630,
    x: 144,
    y: 72,
    row: "4",
    seat: 7,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32631,
    x: 168,
    y: 72,
    row: "4",
    seat: 8,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32632,
    x: 192,
    y: 72,
    row: "4",
    seat: 9,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32633,
    x: 216,
    y: 72,
    row: "4",
    seat: 10,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32634,
    x: 240,
    y: 72,
    row: "4",
    seat: 11,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32635,
    x: 264,
    y: 72,
    row: "4",
    seat: 12,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32636,
    x: 288,
    y: 72,
    row: "4",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32637,
    x: 312,
    y: 72,
    row: "4",
    seat: 14,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32638,
    x: 336,
    y: 72,
    row: "4",
    seat: 15,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32639,
    x: 360,
    y: 72,
    row: "4",
    seat: 16,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32640,
    x: 384,
    y: 72,
    row: "4",
    seat: 17,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32641,
    x: 408,
    y: 72,
    row: "4",
    seat: 18,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32642,
    x: 432,
    y: 72,
    row: "4",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32643,
    x: 456,
    y: 72,
    row: "4",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32644,
    x: 480,
    y: 72,
    row: "4",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32645,
    x: 504,
    y: 72,
    row: "4",
    seat: 22,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32649,
    x: 0,
    y: 96,
    row: "5",
    seat: 1,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32650,
    x: 24,
    y: 96,
    row: "5",
    seat: 2,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32651,
    x: 48,
    y: 96,
    row: "5",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32652,
    x: 72,
    y: 96,
    row: "5",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32653,
    x: 96,
    y: 96,
    row: "5",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32654,
    x: 120,
    y: 96,
    row: "5",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32655,
    x: 144,
    y: 96,
    row: "5",
    seat: 7,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32656,
    x: 168,
    y: 96,
    row: "5",
    seat: 8,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32657,
    x: 192,
    y: 96,
    row: "5",
    seat: 9,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32658,
    x: 216,
    y: 96,
    row: "5",
    seat: 10,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32659,
    x: 240,
    y: 96,
    row: "5",
    seat: 11,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32660,
    x: 264,
    y: 96,
    row: "5",
    seat: 12,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32661,
    x: 288,
    y: 96,
    row: "5",
    seat: 13,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32662,
    x: 312,
    y: 96,
    row: "5",
    seat: 14,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32663,
    x: 336,
    y: 96,
    row: "5",
    seat: 15,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32664,
    x: 360,
    y: 96,
    row: "5",
    seat: 16,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32665,
    x: 384,
    y: 96,
    row: "5",
    seat: 17,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32666,
    x: 408,
    y: 96,
    row: "5",
    seat: 18,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32667,
    x: 432,
    y: 96,
    row: "5",
    seat: 19,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32668,
    x: 456,
    y: 96,
    row: "5",
    seat: 20,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32669,
    x: 480,
    y: 96,
    row: "5",
    seat: 21,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32670,
    x: 504,
    y: 96,
    row: "5",
    seat: 22,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32671,
    x: 528,
    y: 96,
    row: "5",
    seat: 23,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32674,
    x: 0,
    y: 120,
    row: "6",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32675,
    x: 24,
    y: 120,
    row: "6",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32676,
    x: 48,
    y: 120,
    row: "6",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32677,
    x: 72,
    y: 120,
    row: "6",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32678,
    x: 96,
    y: 120,
    row: "6",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32679,
    x: 120,
    y: 120,
    row: "6",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32680,
    x: 144,
    y: 120,
    row: "6",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32681,
    x: 168,
    y: 120,
    row: "6",
    seat: 8,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32682,
    x: 192,
    y: 120,
    row: "6",
    seat: 9,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32683,
    x: 216,
    y: 120,
    row: "6",
    seat: 10,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32684,
    x: 240,
    y: 120,
    row: "6",
    seat: 11,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32685,
    x: 264,
    y: 120,
    row: "6",
    seat: 12,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32686,
    x: 288,
    y: 120,
    row: "6",
    seat: 13,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32687,
    x: 312,
    y: 120,
    row: "6",
    seat: 14,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32688,
    x: 336,
    y: 120,
    row: "6",
    seat: 15,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32689,
    x: 360,
    y: 120,
    row: "6",
    seat: 16,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32690,
    x: 384,
    y: 120,
    row: "6",
    seat: 17,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32691,
    x: 408,
    y: 120,
    row: "6",
    seat: 18,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32692,
    x: 432,
    y: 120,
    row: "6",
    seat: 19,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32693,
    x: 456,
    y: 120,
    row: "6",
    seat: 20,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32694,
    x: 480,
    y: 120,
    row: "6",
    seat: 21,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32695,
    x: 504,
    y: 120,
    row: "6",
    seat: 22,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32696,
    x: 528,
    y: 120,
    row: "6",
    seat: 23,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 32699,
    x: 0,
    y: 144,
    row: "7",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32700,
    x: 24,
    y: 144,
    row: "7",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32701,
    x: 48,
    y: 144,
    row: "7",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32702,
    x: 72,
    y: 144,
    row: "7",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32703,
    x: 96,
    y: 144,
    row: "7",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32704,
    x: 120,
    y: 144,
    row: "7",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32705,
    x: 144,
    y: 144,
    row: "7",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32706,
    x: 168,
    y: 144,
    row: "7",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32707,
    x: 192,
    y: 144,
    row: "7",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32708,
    x: 216,
    y: 144,
    row: "7",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32709,
    x: 240,
    y: 144,
    row: "7",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32710,
    x: 264,
    y: 144,
    row: "7",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32711,
    x: 288,
    y: 144,
    row: "7",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32712,
    x: 312,
    y: 144,
    row: "7",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32713,
    x: 336,
    y: 144,
    row: "7",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32714,
    x: 360,
    y: 144,
    row: "7",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32715,
    x: 384,
    y: 144,
    row: "7",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32716,
    x: 408,
    y: 144,
    row: "7",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32717,
    x: 432,
    y: 144,
    row: "7",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32718,
    x: 456,
    y: 144,
    row: "7",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32719,
    x: 480,
    y: 144,
    row: "7",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32720,
    x: 504,
    y: 144,
    row: "7",
    seat: 22,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32721,
    x: 528,
    y: 144,
    row: "7",
    seat: 23,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32722,
    x: 552,
    y: 144,
    row: "7",
    seat: 24,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32724,
    x: 0,
    y: 168,
    row: "8",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32725,
    x: 24,
    y: 168,
    row: "8",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32726,
    x: 48,
    y: 168,
    row: "8",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32727,
    x: 72,
    y: 168,
    row: "8",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32728,
    x: 96,
    y: 168,
    row: "8",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32729,
    x: 120,
    y: 168,
    row: "8",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32730,
    x: 144,
    y: 168,
    row: "8",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32731,
    x: 168,
    y: 168,
    row: "8",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32732,
    x: 192,
    y: 168,
    row: "8",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32733,
    x: 216,
    y: 168,
    row: "8",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32734,
    x: 240,
    y: 168,
    row: "8",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32735,
    x: 264,
    y: 168,
    row: "8",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32736,
    x: 288,
    y: 168,
    row: "8",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32737,
    x: 312,
    y: 168,
    row: "8",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32738,
    x: 336,
    y: 168,
    row: "8",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32739,
    x: 360,
    y: 168,
    row: "8",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32740,
    x: 384,
    y: 168,
    row: "8",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32741,
    x: 408,
    y: 168,
    row: "8",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32742,
    x: 432,
    y: 168,
    row: "8",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32743,
    x: 456,
    y: 168,
    row: "8",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32744,
    x: 480,
    y: 168,
    row: "8",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32745,
    x: 504,
    y: 168,
    row: "8",
    seat: 22,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32746,
    x: 528,
    y: 168,
    row: "8",
    seat: 23,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32747,
    x: 552,
    y: 168,
    row: "8",
    seat: 24,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32749,
    x: 0,
    y: 192,
    row: "9",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32750,
    x: 24,
    y: 192,
    row: "9",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32751,
    x: 48,
    y: 192,
    row: "9",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32752,
    x: 72,
    y: 192,
    row: "9",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32753,
    x: 96,
    y: 192,
    row: "9",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32754,
    x: 120,
    y: 192,
    row: "9",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32755,
    x: 144,
    y: 192,
    row: "9",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32756,
    x: 168,
    y: 192,
    row: "9",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32757,
    x: 192,
    y: 192,
    row: "9",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32758,
    x: 216,
    y: 192,
    row: "9",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32759,
    x: 240,
    y: 192,
    row: "9",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32760,
    x: 264,
    y: 192,
    row: "9",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32761,
    x: 288,
    y: 192,
    row: "9",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32762,
    x: 312,
    y: 192,
    row: "9",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32763,
    x: 336,
    y: 192,
    row: "9",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32764,
    x: 360,
    y: 192,
    row: "9",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32765,
    x: 384,
    y: 192,
    row: "9",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32766,
    x: 408,
    y: 192,
    row: "9",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32767,
    x: 432,
    y: 192,
    row: "9",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32768,
    x: 456,
    y: 192,
    row: "9",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32769,
    x: 480,
    y: 192,
    row: "9",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32770,
    x: 504,
    y: 192,
    row: "9",
    seat: 22,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32771,
    x: 528,
    y: 192,
    row: "9",
    seat: 23,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32772,
    x: 552,
    y: 192,
    row: "9",
    seat: 24,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32773,
    x: 576,
    y: 192,
    row: "9",
    seat: 25,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32774,
    x: 0,
    y: 216,
    row: "10",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32775,
    x: 24,
    y: 216,
    row: "10",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32776,
    x: 48,
    y: 216,
    row: "10",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32777,
    x: 72,
    y: 216,
    row: "10",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32778,
    x: 96,
    y: 216,
    row: "10",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32779,
    x: 120,
    y: 216,
    row: "10",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32780,
    x: 144,
    y: 216,
    row: "10",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32781,
    x: 168,
    y: 216,
    row: "10",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32782,
    x: 192,
    y: 216,
    row: "10",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32783,
    x: 216,
    y: 216,
    row: "10",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32784,
    x: 240,
    y: 216,
    row: "10",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32785,
    x: 264,
    y: 216,
    row: "10",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32786,
    x: 288,
    y: 216,
    row: "10",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32787,
    x: 312,
    y: 216,
    row: "10",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32788,
    x: 336,
    y: 216,
    row: "10",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32789,
    x: 360,
    y: 216,
    row: "10",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32790,
    x: 384,
    y: 216,
    row: "10",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32791,
    x: 408,
    y: 216,
    row: "10",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32792,
    x: 432,
    y: 216,
    row: "10",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32793,
    x: 456,
    y: 216,
    row: "10",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32794,
    x: 480,
    y: 216,
    row: "10",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32795,
    x: 504,
    y: 216,
    row: "10",
    seat: 22,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32796,
    x: 528,
    y: 216,
    row: "10",
    seat: 23,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 32797,
    x: 552,
    y: 216,
    row: "10",
    seat: 24,
    isSold: false,
    isReserved: true,
    isSelectable: false,
  },
  {
    id: 32798,
    x: 576,
    y: 216,
    row: "10",
    seat: 25,
    isSold: false,
    isReserved: true,
    isSelectable: false,
  },
];
