import { Seat } from "@/types/seat.types";

export const reverseSeats: Seat[] = [
  {
    id: 332319,
    x: 0,
    y: 0,
    row: "1",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332320,
    x: 24,
    y: 0,
    row: "1",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332321,
    x: 48,
    y: 0,
    row: "1",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332322,
    x: 72,
    y: 0,
    row: "1",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332323,
    x: 96,
    y: 0,
    row: "1",
    seat: 15,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332324,
    x: 120,
    y: 0,
    row: "1",
    seat: 14,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332325,
    x: 144,
    y: 0,
    row: "1",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332326,
    x: 168,
    y: 0,
    row: "1",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332327,
    x: 192,
    y: 0,
    row: "1",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332328,
    x: 216,
    y: 0,
    row: "1",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332329,
    x: 240,
    y: 0,
    row: "1",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332330,
    x: 264,
    y: 0,
    row: "1",
    seat: 8,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332331,
    x: 288,
    y: 0,
    row: "1",
    seat: 7,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332332,
    x: 312,
    y: 0,
    row: "1",
    seat: 6,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332333,
    x: 336,
    y: 0,
    row: "1",
    seat: 5,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332334,
    x: 360,
    y: 0,
    row: "1",
    seat: 4,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332335,
    x: 384,
    y: 0,
    row: "1",
    seat: 3,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332336,
    x: 408,
    y: 0,
    row: "1",
    seat: 2,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332337,
    x: 432,
    y: 0,
    row: "1",
    seat: 1,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332343,
    x: 0,
    y: 24,
    row: "2",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332344,
    x: 24,
    y: 24,
    row: "2",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332345,
    x: 48,
    y: 24,
    row: "2",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332346,
    x: 72,
    y: 24,
    row: "2",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332347,
    x: 96,
    y: 24,
    row: "2",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332348,
    x: 120,
    y: 24,
    row: "2",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332349,
    x: 144,
    y: 24,
    row: "2",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332350,
    x: 168,
    y: 24,
    row: "2",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332351,
    x: 192,
    y: 24,
    row: "2",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332352,
    x: 216,
    y: 24,
    row: "2",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332353,
    x: 240,
    y: 24,
    row: "2",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332354,
    x: 264,
    y: 24,
    row: "2",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332355,
    x: 288,
    y: 24,
    row: "2",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332356,
    x: 312,
    y: 24,
    row: "2",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332357,
    x: 336,
    y: 24,
    row: "2",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332358,
    x: 360,
    y: 24,
    row: "2",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332359,
    x: 384,
    y: 24,
    row: "2",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332360,
    x: 408,
    y: 24,
    row: "2",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332361,
    x: 432,
    y: 24,
    row: "2",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332362,
    x: 456,
    y: 24,
    row: "2",
    seat: 1,
    isSold: true,
    isReserved: false,
    isSelectable: false,
  },
  {
    id: 332367,
    x: 0,
    y: 48,
    row: "3",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332368,
    x: 24,
    y: 48,
    row: "3",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332369,
    x: 48,
    y: 48,
    row: "3",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332370,
    x: 72,
    y: 48,
    row: "3",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332371,
    x: 96,
    y: 48,
    row: "3",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332372,
    x: 120,
    y: 48,
    row: "3",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332373,
    x: 144,
    y: 48,
    row: "3",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332374,
    x: 168,
    y: 48,
    row: "3",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332375,
    x: 192,
    y: 48,
    row: "3",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332376,
    x: 216,
    y: 48,
    row: "3",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332377,
    x: 240,
    y: 48,
    row: "3",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332378,
    x: 264,
    y: 48,
    row: "3",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332379,
    x: 288,
    y: 48,
    row: "3",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332380,
    x: 312,
    y: 48,
    row: "3",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332381,
    x: 336,
    y: 48,
    row: "3",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332382,
    x: 360,
    y: 48,
    row: "3",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332383,
    x: 384,
    y: 48,
    row: "3",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332384,
    x: 408,
    y: 48,
    row: "3",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332385,
    x: 432,
    y: 48,
    row: "3",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332386,
    x: 456,
    y: 48,
    row: "3",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332387,
    x: 480,
    y: 48,
    row: "3",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332391,
    x: 0,
    y: 72,
    row: "4",
    seat: 22,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332392,
    x: 24,
    y: 72,
    row: "4",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332393,
    x: 48,
    y: 72,
    row: "4",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332394,
    x: 72,
    y: 72,
    row: "4",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332395,
    x: 96,
    y: 72,
    row: "4",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332396,
    x: 120,
    y: 72,
    row: "4",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332397,
    x: 144,
    y: 72,
    row: "4",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332398,
    x: 168,
    y: 72,
    row: "4",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332399,
    x: 192,
    y: 72,
    row: "4",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332400,
    x: 216,
    y: 72,
    row: "4",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332401,
    x: 240,
    y: 72,
    row: "4",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332402,
    x: 264,
    y: 72,
    row: "4",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332403,
    x: 288,
    y: 72,
    row: "4",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332404,
    x: 312,
    y: 72,
    row: "4",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332405,
    x: 336,
    y: 72,
    row: "4",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332406,
    x: 360,
    y: 72,
    row: "4",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332407,
    x: 384,
    y: 72,
    row: "4",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332408,
    x: 408,
    y: 72,
    row: "4",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332409,
    x: 432,
    y: 72,
    row: "4",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332410,
    x: 456,
    y: 72,
    row: "4",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332411,
    x: 480,
    y: 72,
    row: "4",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332412,
    x: 504,
    y: 72,
    row: "4",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332415,
    x: 0,
    y: 96,
    row: "5",
    seat: 23,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332416,
    x: 24,
    y: 96,
    row: "5",
    seat: 22,
    isSold: false,
    isReserved: true,
    isSelectable: false,
  },
  {
    id: 332417,
    x: 48,
    y: 96,
    row: "5",
    seat: 21,
    isSold: false,
    isReserved: true,
    isSelectable: false,
  },
  {
    id: 332418,
    x: 72,
    y: 96,
    row: "5",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332419,
    x: 96,
    y: 96,
    row: "5",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332420,
    x: 120,
    y: 96,
    row: "5",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332421,
    x: 144,
    y: 96,
    row: "5",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332422,
    x: 168,
    y: 96,
    row: "5",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332423,
    x: 192,
    y: 96,
    row: "5",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332424,
    x: 216,
    y: 96,
    row: "5",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332425,
    x: 240,
    y: 96,
    row: "5",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332426,
    x: 264,
    y: 96,
    row: "5",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332427,
    x: 288,
    y: 96,
    row: "5",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332428,
    x: 312,
    y: 96,
    row: "5",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332429,
    x: 336,
    y: 96,
    row: "5",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332430,
    x: 360,
    y: 96,
    row: "5",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332431,
    x: 384,
    y: 96,
    row: "5",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332432,
    x: 408,
    y: 96,
    row: "5",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332433,
    x: 432,
    y: 96,
    row: "5",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332434,
    x: 456,
    y: 96,
    row: "5",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332435,
    x: 480,
    y: 96,
    row: "5",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332436,
    x: 504,
    y: 96,
    row: "5",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332437,
    x: 528,
    y: 96,
    row: "5",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332439,
    x: 0,
    y: 120,
    row: "6",
    seat: 24,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332440,
    x: 24,
    y: 120,
    row: "6",
    seat: 23,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332441,
    x: 48,
    y: 120,
    row: "6",
    seat: 22,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332442,
    x: 72,
    y: 120,
    row: "6",
    seat: 21,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332443,
    x: 96,
    y: 120,
    row: "6",
    seat: 20,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332444,
    x: 120,
    y: 120,
    row: "6",
    seat: 19,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332445,
    x: 144,
    y: 120,
    row: "6",
    seat: 18,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332446,
    x: 168,
    y: 120,
    row: "6",
    seat: 17,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332447,
    x: 192,
    y: 120,
    row: "6",
    seat: 16,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332448,
    x: 216,
    y: 120,
    row: "6",
    seat: 15,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332449,
    x: 240,
    y: 120,
    row: "6",
    seat: 14,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332450,
    x: 264,
    y: 120,
    row: "6",
    seat: 13,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332451,
    x: 288,
    y: 120,
    row: "6",
    seat: 12,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332452,
    x: 312,
    y: 120,
    row: "6",
    seat: 11,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332453,
    x: 336,
    y: 120,
    row: "6",
    seat: 10,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332454,
    x: 360,
    y: 120,
    row: "6",
    seat: 9,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332455,
    x: 384,
    y: 120,
    row: "6",
    seat: 8,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332456,
    x: 408,
    y: 120,
    row: "6",
    seat: 7,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332457,
    x: 432,
    y: 120,
    row: "6",
    seat: 6,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332458,
    x: 456,
    y: 120,
    row: "6",
    seat: 5,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332459,
    x: 480,
    y: 120,
    row: "6",
    seat: 4,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332460,
    x: 504,
    y: 120,
    row: "6",
    seat: 3,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332461,
    x: 528,
    y: 120,
    row: "6",
    seat: 2,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
  {
    id: 332462,
    x: 552,
    y: 120,
    row: "6",
    seat: 1,
    isSold: false,
    isReserved: false,
    isSelectable: true,
  },
];
