import { Seat } from "@/types/seat.types";

export const theatreSeats: Seat[] = [
  {
    id: 1,
    x: -72.0,
    y: 0.0,
    row: "1",
    seat: 1,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 2,
    x: -68.48,
    y: 22.25,
    row: "1",
    seat: 2,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 3,
    x: -58.25,
    y: 42.32,
    row: "1",
    seat: 3,
    isSold: false,
    isSelectable: false,
    isReserved: true,
  },
  {
    id: 4,
    x: -42.32,
    y: 58.25,
    row: "1",
    seat: 4,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 5,
    x: -22.25,
    y: 68.48,
    row: "1",
    seat: 5,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 6,
    x: 0.0,
    y: 72.0,
    row: "1",
    seat: 6,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 7,
    x: 24.25,
    y: 72.0,
    row: "1",
    seat: 7,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 8,
    x: 42.32,
    y: 58.25,
    row: "1",
    seat: 8,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 9,
    x: 58.25,
    y: 42.32,
    row: "1",
    seat: 9,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 10,
    x: 68.48,
    y: 22.25,
    row: "1",
    seat: 10,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 11,
    x: 72.0,
    y: 0.0,
    row: "1",
    seat: 11,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 12,
    x: -96.0,
    y: 0.0,
    row: "2",
    seat: 1,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 13,
    x: -92.73,
    y: 24.85,
    row: "2",
    seat: 2,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 14,
    x: -83.14,
    y: 48.0,
    row: "2",
    seat: 3,
    isSold: false,
    isSelectable: false,
    isReserved: true,
  },
  {
    id: 15,
    x: -67.88,
    y: 67.88,
    row: "2",
    seat: 4,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 16,
    x: -48.0,
    y: 83.14,
    row: "2",
    seat: 5,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 17,
    x: -24.85,
    y: 92.73,
    row: "2",
    seat: 6,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 18,
    x: 0.0,
    y: 96.0,
    row: "2",
    seat: 7,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 19,
    x: 24.85,
    y: 92.73,
    row: "2",
    seat: 8,
    isSold: false,
    isSelectable: false,
    isReserved: true,
  },
  {
    id: 20,
    x: 48.0,
    y: 83.14,
    row: "2",
    seat: 9,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 21,
    x: 67.88,
    y: 67.88,
    row: "2",
    seat: 10,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 22,
    x: 83.14,
    y: 48.0,
    row: "2",
    seat: 11,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 23,
    x: 92.73,
    y: 24.85,
    row: "2",
    seat: 12,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 24,
    x: 96.0,
    y: 0.0,
    row: "2",
    seat: 13,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 25,
    x: -120.0,
    y: 0.0,
    row: "3",
    seat: 1,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 26,
    x: -116.99,
    y: 26.7,
    row: "3",
    seat: 2,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 27,
    x: -108.11,
    y: 52.07,
    row: "3",
    seat: 3,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 28,
    x: -93.82,
    y: 74.82,
    row: "3",
    seat: 4,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 29,
    x: -74.82,
    y: 93.82,
    row: "3",
    seat: 5,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 30,
    x: -52.07,
    y: 108.11,
    row: "3",
    seat: 6,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 31,
    x: -26.7,
    y: 116.99,
    row: "3",
    seat: 7,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 32,
    x: 0.0,
    y: 120.0,
    row: "3",
    seat: 8,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 33,
    x: 26.7,
    y: 116.99,
    row: "3",
    seat: 9,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 34,
    x: 52.07,
    y: 108.11,
    row: "3",
    seat: 10,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 35,
    x: 74.82,
    y: 93.82,
    row: "3",
    seat: 11,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 36,
    x: 93.82,
    y: 74.82,
    row: "3",
    seat: 12,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 37,
    x: 108.11,
    y: 52.07,
    row: "3",
    seat: 13,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 38,
    x: 116.99,
    y: 26.7,
    row: "3",
    seat: 14,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 39,
    x: 120.0,
    y: 0.0,
    row: "3",
    seat: 15,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 40,
    x: -144.0,
    y: 0.0,
    row: "4",
    seat: 1,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 41,
    x: -141.23,
    y: 28.09,
    row: "4",
    seat: 2,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 42,
    x: -133.04,
    y: 55.1,
    row: "4",
    seat: 3,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 43,
    x: -119.73,
    y: 80.0,
    row: "4",
    seat: 4,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 44,
    x: -101.83,
    y: 101.83,
    row: "4",
    seat: 5,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 45,
    x: -80.0,
    y: 119.73,
    row: "4",
    seat: 6,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 46,
    x: -55.1,
    y: 133.04,
    row: "4",
    seat: 7,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 47,
    x: -28.09,
    y: 141.23,
    row: "4",
    seat: 8,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 48,
    x: 0.0,
    y: 144.0,
    row: "4",
    seat: 9,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 49,
    x: 28.09,
    y: 141.23,
    row: "4",
    seat: 10,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 50,
    x: 55.1,
    y: 133.04,
    row: "4",
    seat: 11,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 51,
    x: 80.0,
    y: 119.73,
    row: "4",
    seat: 12,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 52,
    x: 101.83,
    y: 101.83,
    row: "4",
    seat: 13,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 53,
    x: 119.73,
    y: 80.0,
    row: "4",
    seat: 14,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 54,
    x: 133.04,
    y: 55.1,
    row: "4",
    seat: 15,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 55,
    x: 141.23,
    y: 28.09,
    row: "4",
    seat: 16,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 56,
    x: 144.0,
    y: 0.0,
    row: "4",
    seat: 17,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 57,
    x: -168.0,
    y: 0.0,
    row: "5",
    seat: 1,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 58,
    x: -165.45,
    y: 29.17,
    row: "5",
    seat: 2,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 59,
    x: -157.87,
    y: 57.46,
    row: "5",
    seat: 3,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 60,
    x: -145.49,
    y: 84.0,
    row: "5",
    seat: 4,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 61,
    x: -128.69,
    y: 107.99,
    row: "5",
    seat: 5,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 62,
    x: -107.99,
    y: 128.69,
    row: "5",
    seat: 6,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 63,
    x: -84.0,
    y: 145.49,
    row: "5",
    seat: 7,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 64,
    x: -57.46,
    y: 157.87,
    row: "5",
    seat: 8,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 65,
    x: -29.17,
    y: 165.45,
    row: "5",
    seat: 9,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 66,
    x: 0.0,
    y: 168.0,
    row: "5",
    seat: 10,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 67,
    x: 29.17,
    y: 165.45,
    row: "5",
    seat: 11,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 68,
    x: 57.46,
    y: 157.87,
    row: "5",
    seat: 12,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 69,
    x: 84.0,
    y: 145.49,
    row: "5",
    seat: 13,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 70,
    x: 107.99,
    y: 128.69,
    row: "5",
    seat: 14,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 71,
    x: 128.69,
    y: 107.99,
    row: "5",
    seat: 15,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 72,
    x: 145.49,
    y: 84.0,
    row: "5",
    seat: 16,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 73,
    x: 157.87,
    y: 57.46,
    row: "5",
    seat: 17,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 74,
    x: 165.45,
    y: 29.17,
    row: "5",
    seat: 18,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 75,
    x: 168.0,
    y: 0.0,
    row: "5",
    seat: 19,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 76,
    x: -192.0,
    y: 0.0,
    row: "6",
    seat: 1,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 77,
    x: -189.64,
    y: 30.04,
    row: "6",
    seat: 2,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 78,
    x: -182.6,
    y: 59.33,
    row: "6",
    seat: 3,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 79,
    x: -171.07,
    y: 87.17,
    row: "6",
    seat: 4,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 80,
    x: -155.33,
    y: 112.85,
    row: "6",
    seat: 5,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 81,
    x: -135.76,
    y: 135.76,
    row: "6",
    seat: 6,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 82,
    x: -112.85,
    y: 155.33,
    row: "6",
    seat: 7,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 83,
    x: -87.17,
    y: 171.07,
    row: "6",
    seat: 8,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 84,
    x: -59.33,
    y: 182.6,
    row: "6",
    seat: 9,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 85,
    x: -30.04,
    y: 189.64,
    row: "6",
    seat: 10,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 86,
    x: 0.0,
    y: 192.0,
    row: "6",
    seat: 11,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 87,
    x: 30.04,
    y: 189.64,
    row: "6",
    seat: 12,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 88,
    x: 59.33,
    y: 182.6,
    row: "6",
    seat: 13,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 89,
    x: 87.17,
    y: 171.07,
    row: "6",
    seat: 14,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 90,
    x: 112.85,
    y: 155.33,
    row: "6",
    seat: 15,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 91,
    x: 135.76,
    y: 135.76,
    row: "6",
    seat: 16,
    isSold: true,
    isSelectable: false,
    isReserved: false,
  },
  {
    id: 92,
    x: 155.33,
    y: 112.85,
    row: "6",
    seat: 17,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 93,
    x: 171.07,
    y: 87.17,
    row: "6",
    seat: 18,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 94,
    x: 182.6,
    y: 59.33,
    row: "6",
    seat: 19,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 95,
    x: 189.64,
    y: 30.04,
    row: "6",
    seat: 20,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
  {
    id: 96,
    x: 192.0,
    y: 0.0,
    row: "6",
    seat: 21,
    isSold: false,
    isSelectable: true,
    isReserved: false,
  },
];
